### PR TITLE
Fix render.download not working in Express

### PR DESCRIPTION
**Pull request by jcheng5**
@gadenbuie Did I put the Express example in the right place?

### CODE REVIEW

**Comment by gadenbuie** [comment]
> @gadenbuie Did I put the Express example in the right place?

Yup, the example's in the right place. 👍

**Comment by jcheng5** [comment]
The Playwright failures appear to be real!? api-examples/Progress/app-express.py is throwing an error `shiny.express.input can only be used inside of a Shiny Express app` upon startup.

**Comment by gadenbuie** [comment]
The issue specifically depends on _using_ a `reactive.effect(input.___)`. Here's a minimal reprex -- uncommenting the `@reactive.effect()` introduces the error:

```python
from shiny import reactive
from shiny.express import input, render, ui

ui.input_text_area(
    "caption",
    "Caption:",
    "Here's a caption.",
)

ui.input_action_button("btn", "Update")


@render.text
# @reactive.effect(input.btn)
def value_regular():
    return input.caption()
```

**Comment by wch** [comment]
Shouldn't it be `reactive.event`, not `reactive.effect`?

**Comment by gadenbuie** [comment]
> Shouldn't it be `reactive.event`, not `reactive.effect`?

Yes it should, but `reactive.effect()` introduces the bug. I'll update the example, htough

**Comment by gadenbuie** [comment]
In case it matters to anyone, I found the source of the bug:

https://github.com/posit-dev/py-shiny/blob/fc55acc329aa663eab718e6a222bb72547135490/shiny/session/_utils.py#L57

should be

```python
    cs = _current_session.get()
    return cs if cs is not None else _default_session
```

**Comment by wch** [comment]
@gadenbuie good find! I feel like falsiness in general causes more problems than it helps with. I think we should fix that in another PR.

**Comment by wch** [comment]
Closing because this was fixed by #1085.

**Pull request closed without merging**
