### PR TITLE
`express.ui.page_opts(title = ...)` now always generates a header

### LINKED ISSUE #1015: `express.ui.page_opts(title = ...)` is sometimes not visible on the page
For example, the `Foo` here isn't visible on the page (it only gets used for the browser tab's title)

```python
from shiny.express import ui

ui.page_opts(title="Foo")

"Bar"
```

For consistency, `ui.page_opts(title="Foo")` should always generate a visible result

### PR DESCRIPTION
**Pull request by cpsievert**
Closes #1015

### CODE REVIEW

**Comment by wch** [comment]
It would be useful to be able to set the window title separately from the on-page title. How about having two separate args, `window_title` and `title`, and if `window_title` isn't provided, it defaults to the value of `title`?

**Comment by cpsievert** [comment]
Yea, we can definitely add that, but I think it'll time a bit of time to do properly, let's maybe add that as an item for the next release and take this now?

**Comment by wch** [comment]
I just went ahead and implemented the `window_title` and `title` behavior.

**Comment by wch** [comment]
Interesting... `title` is expected to be a string based on the type hints, but I suppose it is possible that someone would pass in a `Tag`/`Taglist` object. I'll file an issue about it.

**Pull request merged**
