### PR TITLE
Render `shiny.min.css` using `bs_theme()`

### PR DESCRIPTION
**Pull request by gadenbuie**
Currently, we're using `shiny.min.css` directly, which does not include Bootstrap 5 adjustments. The most notable place this causes problems is with the notifications messages, which are currently using partially incorrect styles. ([Example app](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxMAkhFQBXMiwkB5eXIUSAynBYsOpCXThRCZDgDc4E2RwA6EO2lQB9a0wC8Ta1igBzOE5oAG2sAEwAKOyYozw4MLjUnY1NSJwAjeTJSCLB2YgB3G3wmQo02fMKASjxI6MLi-Bqor3j5RJM9CDSMrMLDGGILQolCgCU4fsGwKrsKuzmIELgaVjg6CzowlrJEKRl5RSZiVXkdlTI1A5ZtXVIdrR0OisRG3hCWHcCOFjJgb7oAXXcTGA-xeEB2XGEHgADPNokwAAKGJLmOAYACiNBocBMLyRRnaFgwcAs5E2ezIGFyeVmEHhi2WTjCTxe8IgpECxEIUECrxYrOi7IgnO5vPsdPh0QAxEwNFALEwyGw4FIACJMGiCJh9AY8piBKAUOgCqIcEJArzs0w0Djc5KdanZACy118KrqAGpWGQNhAqkwQrI6IaOm4AHKkOC0yXRM0sDCOSjhM3RmNMOkejwARjh0XxKKJmOxuIlUXzhLRJMoZHJagwOosqaiDKYTJZpclQpFerjJt4yzjzw7aZiGCtHBtdo6TgbcE2bywxFQzNp80cQLEy8cLg4Eiua1WEkW6R8bgAKnRZFH5mAAL7-IA))

image

After this change, we re-render `shiny.min.css` using the `bs_theme()` object, which gives us better looking notifications.

image

Also while here, I updated the update script to use `cli` if availble for a much cleaner log experience.

```
❯ Rscript scripts/htmlDependencies.R
✔ Checking for node / npm [41ms]
✔ Installing GitHub packages: bslib, shiny, htmltools [5.8s]
✔ Copy shiny www/shared [320ms]
✔ Copy bslib components [49ms]
✔ Copy htmltools - fill [24ms]
✔ Cleanup shiny www/shared [13ms]
✔ Save ionRangeSlider dep [394ms]
✔ Save bootstrap bundle [506ms]
✔ Reduce font files [23ms]
✔ Render shiny.min.css with bs_theme() [52ms]
✔ Render selectize.min.js with bs_theme() [60ms]
✔ Render datepicker.min.css with bs_theme() [63ms]
✔ Cleanup bootstrap bundle [18ms]
✔ Save requirejs [144ms]
✔ Save _versions.py [9ms]
```

I applied the same process to other dependencies from `shiny`:

* shiny
* selectize
* datepicker

### CODE REVIEW

**Comment by cpsievert** [comment]
Thanks! I'm pretty sure we should doing the same for `selectize.css`

**Review by schloerke — APPROVED** [review]

**Comment by schloerke** [comment]
Do we need to do the same for shinyswatch?

**Comment by gadenbuie** [comment]
> Do we need to do the same for shinyswatch?

I'm not sure... I thought shinyswatch was replacing just the Boostrap CSS. If it included these component CSS files, I'd imagine you're already running `bs_theme()` through them.

We'd like to move toward a setup where we can replace the core Bootstrap CSS and have these component files work via CSS variables. I think we're _close_ here but there might be places where we need to update the CSS upstream in rstudio/shiny.

**Comment by schloerke** [comment]
From https://github.com/posit-dev/py-shinyswatch/tree/e6f097b792bbba61fc4c03b0bbc78e4ae422f0c1/shinyswatch/bsw5/cerulean , shinyswatch is only aware of the ionRangeSlider and is missing `selectize` and `datepicker`. 

May I request a PR to add those two files? Thank you!

**Comment by gadenbuie** [comment]
With this change, shinyswatch shouldn't need to do anything with ionRangeSlider. I'll take a look

**Pull request merged**
