### PR TITLE
feat(df): Make `.input_cell_selection()` return a consistent type shape; Change row order to data view row order

### PR DESCRIPTION
**Pull request by schloerke**
~~Should be rebased after #1374 is merged!~~

TODO
- ~~Merge #1374~~
- ~~Rebase to `main`~~
- ~~Change merge branch to `main`… (or `rows`) tuple containing all column (or row) numbers~~

** Update merging into #1374 to get changes

--------------------------

Features for `.input_cell_selection()`:
* Removed `None` return type
* Added missing `cols` (or `rows`) when the `input` object sent across the wire does not contain the values.
* Row order is now ordered as if it is being subsetted from Data View row order

Note:
`input.<ID>_cell_selection()`'s shape did not change. It does not contain missing `cols` (or `rows`) as that information is always unnecessary.  

(However, this leads to an awkward user interaction with the code, so `<ID>.input_cell_selection()` upgrades the return value to support the missing keys.)

--------------------------

Previous return type for `.input_cell_selection()`:

```python
class CellSelectionNone(TypedDict):
    type: Literal["none"]

class CellSelectionRow(TypedDict):
    type: Literal["row"]
    rows: ListOrTuple[int]

class CellSelectionCol(TypedDict):
    type: Literal["col"]
    cols: ListOrTuple[int]

class CellSelectionRect(TypedDict):
    type: Literal["rect"]
    # Attempt to type the list of size 2, but it is not type enforced
    rows: tuple[int, int] | Annotated[list[int], 2]
    cols: tuple[int, int] | Annotated[list[int], 2]

CellSelection = Union[
    CellSelectionRow,
    CellSelectionCol,
    CellSelectionRect,
    CellSelectionNone,
]

def .input_cell_selection() -> CellSelection | None:
```

New return type for `.input_cell_selection()`:

```python
class CellSelection(TypedDict):
    type: Literal["none", "row", "col", "rect"]
    rows: ListOrTuple[int]
    cols: ListOrTuple[int]

def .input_cell_selection() -> CellSelection:
```

* If `type = "none"`, `rows` and `cols` are empty tuples. 
* If `type = "row"`, `cols` is all column numbers of the data.
* If `type = "col"`, `rows` is all row numbers of the data view rows
* If `type = "rect"`, all rows and cols are provided (no longer just min/max values). 

-------------------------

Previous user interaction: 

```python
@render.data_frame
def grid(): ...

selected_rows = (grid.input_cell_selection() or {}).get("rows", ())
```

New user interaction:

```python
selected_rows = grid.input_cell_selection()["rows"]
```

### CODE REVIEW

**Comment by wch** [comment]
Note that after we release this, we'll need to update the examples in py-shiny-site.

**Review by wch — APPROVED** [review]

**Comment by schloerke** [comment]
From https://github.com/posit-dev/py-shiny/pull/1374#issuecomment-2118100523
> Also, input_cell_selection rows should be ordered the way the user sees it.

**Comment by schloerke** [comment]
@jcheng5 `None` support within `.input_cell_selection()` feels wonky. Should it instead throw a `req(False)`?

**Comment by schloerke** [comment]
Squash merging into base branch for easier PR interactions as `main` is frozen for v0.10.0 release

**Pull request merged**
